# Generated by Django 4.0.4 on 2022-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('genre', models.PositiveSmallIntegerField(choices=[(4, 'Romance'), (0, 'Action and Adventure'), (3, 'Horror/Thriller'), (1, 'Fantasy'), (1, 'Classics'), (5, 'Biography'), (2, 'Science Fiction')], default=0)),
            ],
        ),
    ]
